version: "3.5"
services:
  redis:
    image: redis
  backend:
    image: back
    build: ./back/
    ports:
     - 8000:8000
    environment:
     - REDIS=redis
  frontend:
    image: front
    build: ./front/
    ports:
     - 5000:5000
