version: "3.5"
services:
  redis:
    image: redis
  backend:
    image: back
    build: ./back/
    ports:
     - 8000:8000
    environment:
     - REDIS=redis
     - DB_USERNAME=docker
     - DB_PASSWORD=docker
     - DB_HOST=database
  database:
    image: postgres
    restart: unless-stopped
    environment:
     - POSTGRES_USER=docker
     - POSTGRES_PASSWORD=docker
    volumes:
     - ./database:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
     - 80:80
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
     - frontend
     - backend
  frontend:
    image: front
    build: ./front/
    ports:
     - 5000:5000
