version: "3"
services:
    backend:
      image: back
      environment:
        - FRONT_URL=http://localhost:5000
      ports: 
        - 8000:8000
      volumes:
        - ./logs.txt:/back/logs.txt
    frontend:
      image: front
      environment:
        - API_URL=http://localhost:8000
      ports:
        - 5000:5000
